spring:
  datasource:
    url: jdbc:mysql://192.168.1.140:3307/common?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  redis:
    host: 192.168.1.141

eureka:
  client:
    service-url:
      defaultZone: http://yzf:yzf123eureka@localhost:8379/eureka/

logging:
  config: classpath:log/logback-dev.xml

app:
  weixin:
    wx-domain-url: empty
    wx-appid: empty
    wx-secret: empty
  nanjing:
    cro-url: http://yzf2015.imwork.net:8071/cro/
    is-active: true
